### ISSUE TITLE
If I want to train my own dataset, Where can I modify the anchor?

### ISSUE THREAD

**Issue by LDoubleZhi** [TencentYoutuResearch/ObjectDetection-OneStageDet#13]

**Comment by LDoubleZhi** [comment]
I only modify the labels  and batchsize in yolov3.yml. When I training on my own datset, I find obj =0.0000 almost account for 70% in the logs.I think maybe I should modify the anchor for my own datset whereas VOC2007

**Comment by mileistone** [comment]
yolo/vedanet/models/_yolov3.py
