### ISSUE TITLE
多GPU训练

### ISSUE THREAD

**Issue by fengxiuyaun** [TencentYoutuResearch/ObjectDetection-OneStageDet#14]
您好，请问，1. 多GPU怎么训练呢？需要修改什么地方的代码？2. 我使用您给的原网络配置，训练yolov3，总是会内存不够，把batchsize设置为16才勉强训练，但是显然16太小。您是怎么训的呢？

**Comment by mileistone** [comment]
you should use smaller `mini_batch_size` not smaller `batch_size`
