### ISSUE TITLE
ImportError: /home/lele/pytorch/ObjectDetection-OneStageDet/yolo/utils/test/nms/gpu_nms.so: undefined symbol: _Py_ZeroStruct

### ISSUE THREAD

**Issue by lele12** [TencentYoutuResearch/ObjectDetection-OneStageDet#15]
你好
当我编译 utils/test 时,编译成功了,但当我运行python train.py Yolov3时遇到了,下面的报错.
我把python的默认版本从python2.7改为python3.6 编译后运行,依然出现同样的错误.
期望你的回复,谢谢
Traceback (most recent call last):
  File "/home/lele/pytorch/ObjectDetection-OneStageDet/yolo/examples/train.py", line 15, in <module>
    import vedanet as vn
  File "/home/lele/pytorch/ObjectDetection-OneStageDet/yolo/vedanet/__init__.py", line 13, in <module>
    from . import engine
  File "/home/lele/pytorch/ObjectDetection-OneStageDet/yolo/vedanet/engine/__init__.py", line 10, in <module>
    from ._voc_test import *
  File "/home/lele/pytorch/ObjectDetection-OneStageDet/yolo/vedanet/engine/_voc_test.py", line 10, in <module>
    from utils.test import voc_wrapper
  File "/home/lele/pytorch/ObjectDetection-OneStageDet/yolo/utils/test/voc_wrapper.py", line 4, in <module>
    from .fast_rcnn.nms_wrapper import nms, soft_nms
  File "/home/lele/pytorch/ObjectDetection-OneStageDet/yolo/utils/test/fast_rcnn/nms_wrapper.py", line 8, in <module>
    from ..nms.gpu_nms import gpu_nms
ImportError: /home/lele/pytorch/ObjectDetection-OneStageDet/yolo/utils/test/nms/gpu_nms.so: undefined symbol: _Py_ZeroStruct

**Comment by mileistone** [comment]
Your ` utils/test` compilation has some problem, maybe your compilation is based on python2.7, but you use it on python3.6

**Comment by lele12** [comment]
你好,谢谢你的指导,但我编译时也是用的python3.6,运行代码也是用的python3.6.依然不能运行.
下面是我编译的日志.
期望你的回复,谢谢
python setup.py build_ext --inplace
running build_ext
skipping 'utils/bbox.c' Cython extension (up-to-date)
building 'utils.cython_bbox' extension
creating build
creating build/temp.linux-x86_64-3.6
creating build/temp.linux-x86_64-3.6/utils
x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -I/usr/local/lib/python3.6/dist-packages/numpy/core/include -I/usr/include/python3.6m -c utils/bbox.c -o build/temp.linux-x86_64-3.6/utils/bbox.o -Wno-cpp -Wno-unused-function
x86_64-linux-gnu-gcc -pthread -shared -Wl,-O1 -Wl,-Bsymbolic-functions -Wl,-Bsymbolic-functions -Wl,-z,relro -Wl,-Bsymbolic-functions -Wl,-z,relro -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 build/temp.linux-x86_64-3.6/utils/bbox.o -o /home/lele/pytorch/ObjectDetection-OneStageDet/yolo/utils/test/utils/cython_bbox.cpython-36m-x86_64-linux-gnu.so
skipping 'nms/cpu_nms.c' Cython extension (up-to-date)
building 'nms.cpu_nms' extension
creating build/temp.linux-x86_64-3.6/nms
x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -I/usr/local/lib/python3.6/dist-packages/numpy/core/include -I/usr/include/python3.6m -c nms/cpu_nms.c -o build/temp.linux-x86_64-3.6/nms/cpu_nms.o -Wno-cpp -Wno-unused-function
x86_64-linux-gnu-gcc -pthread -shared -Wl,-O1 -Wl,-Bsymbolic-functions -Wl,-Bsymbolic-functions -Wl,-z,relro -Wl,-Bsymbolic-functions -Wl,-z,relro -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 build/temp.linux-x86_64-3.6/nms/cpu_nms.o -o /home/lele/pytorch/ObjectDetection-OneStageDet/yolo/utils/test/nms/cpu_nms.cpython-36m-x86_64-linux-gnu.so
skipping 'nms/gpu_nms.cpp' Cython extension (up-to-date)
building 'nms.gpu_nms' extension
/usr/local/cuda/bin/nvcc -I/usr/local/lib/python3.6/dist-packages/numpy/core/include -I/usr/local/cuda/include -I/usr/include/python3.6m -c nms/nms_kernel.cu -o build/temp.linux-x86_64-3.6/nms/nms_kernel.o -arch=sm_35 --ptxas-options=-v -c --compiler-options '-fPIC'
ptxas info    : 0 bytes gmem
ptxas info    : Compiling entry function '_Z10nms_kernelifPKfPy' for 'sm_35'
ptxas info    : Function properties for _Z10nms_kernelifPKfPy
    0 bytes stack frame, 0 bytes spill stores, 0 bytes spill loads
ptxas info    : Used 25 registers, 1280 bytes smem, 344 bytes cmem[0], 8 bytes cmem[2]
x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -I/usr/local/lib/python3.6/dist-packages/numpy/core/include -I/usr/local/cuda/include -I/usr/include/python3.6m -c nms/gpu_nms.cpp -o build/temp.linux-x86_64-3.6/nms/gpu_nms.o -Wno-unused-function
In file included from /usr/local/lib/python3.6/dist-packages/numpy/core/include/numpy/ndarraytypes.h:1822:0,
                 from /usr/local/lib/python3.6/dist-packages/numpy/core/include/numpy/ndarrayobject.h:12,
                 from /usr/local/lib/python3.6/dist-packages/numpy/core/include/numpy/arrayobject.h:4,
                 from nms/gpu_nms.cpp:581:
/usr/local/lib/python3.6/dist-packages/numpy/core/include/numpy/npy_1_7_deprecated_api.h:17:2: warning: #warning "Using deprecated NumPy API, disable it with " "#define NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION" [-Wcpp]
 #warning "Using deprecated NumPy API, disable it with " \
  ^
x86_64-linux-gnu-g++ -pthread -shared -Wl,-O1 -Wl,-Bsymbolic-functions -Wl,-Bsymbolic-functions -Wl,-z,relro -Wl,-Bsymbolic-functions -Wl,-z,relro -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 build/temp.linux-x86_64-3.6/nms/nms_kernel.o build/temp.linux-x86_64-3.6/nms/gpu_nms.o -L/usr/local/cuda/lib64 -Wl,--enable-new-dtags,-R/usr/local/cuda/lib64 -lcudart -o /home/lele/pytorch/ObjectDetection-OneStageDet/yolo/utils/test/nms/gpu_nms.cpython-36m-x86_64-linux-gnu.so
skipping 'pycocotools/_mask.c' Cython extension (up-to-date)
building 'pycocotools._mask' extension
creating build/temp.linux-x86_64-3.6/pycocotools
x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -I/usr/local/lib/python3.6/dist-packages/numpy/core/include -Ipycocotools -I/usr/include/python3.6m -c pycocotools/maskApi.c -o build/temp.linux-x86_64-3.6/pycocotools/maskApi.o -Wno-cpp -Wno-unused-function -std=c99
x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -I/usr/local/lib/python3.6/dist-packages/numpy/core/include -Ipycocotools -I/usr/include/python3.6m -c pycocotools/_mask.c -o build/temp.linux-x86_64-3.6/pycocotools/_mask.o -Wno-cpp -Wno-unused-function -std=c99
x86_64-linux-gnu-gcc -pthread -shared -Wl,-O1 -Wl,-Bsymbolic-functions -Wl,-Bsymbolic-functions -Wl,-z,relro -Wl,-Bsymbolic-functions -Wl,-z,relro -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 build/temp.linux-x86_64-3.6/pycocotools/maskApi.o build/temp.linux-x86_64-3.6/pycocotools/_mask.o -o /home/lele/pytorch/ObjectDetection-OneStageDet/yolo/utils/test/pycocotools/_mask.cpython-36m-x86_64-linux-gnu.so
rm -rf build

**Comment by mileistone** [comment]
I didn't encounter a problem like that. You could solve it by google, or just use a python version nms which doesn't need compilation.
