### ISSUE TITLE
多GPU训练Yolov3

### ISSUE THREAD

**Issue by saigequn** [TencentYoutuResearch/ObjectDetection-OneStageDet#16]
两个GPU训练Yolov3

yolov3.yml修改
```
gpus: "0,1"
mini_batch_size:8
```

GPU使用情况如下
```
Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  Tesla P100-PCIE...  Off  | 00000000:05:00.0 Off |                    0 |
| N/A   58C    P0   237W / 250W |   8835MiB / 16160MiB |     100%      Default|
+-------------------------------+----------------------+----------------------+
|   1  Tesla P100-PCIE...  Off  | 00000000:89:00.0 Off |                    0 |
| N/A   36C    P0    25W / 250W |     11MiB / 16160MiB |      0%      Default 
```

其中一个GPU在闲置

**Comment by mileistone** [comment]
We don't support multi gpus now. It's easy, you can implement it in 10 minutes.

**Comment by tonysy** [comment]
Could you share how to revise the code to achieve multi-gpu train? I found it difficult to implement.

**Comment by yutaizhou** [comment]
Can you share a guide on multi gpu implementation? Or give some good resources?

**Comment by gongh4** [comment]
First, update the cfg set gpus:"0,1"
Then, in _voc_train.py, insert the code after
if self.cuda:
     net.cuda()
as 
net.net = torch.nn.DataParallel(net.net)

Then, you can train using multi-gpu
