### ISSUE TITLE
Would you give a simple demo about img detection or video detection just like other project.......

### ISSUE THREAD

**Issue by LDoubleZhi** [TencentYoutuResearch/ObjectDetection-OneStageDet#21]

**Comment by ersanliqiao** [comment]
Yes, I have the same question.

**Comment by fourth-archive** [comment]
This repo has excellent demos. It even has a YOLOv3 iPhone app!
https://github.com/ultralytics/yolov3/

**Comment by Stinky-Tofu** [comment]
I have a better code about yolo https://github.com/Stinky-Tofu/Stronger-yolo

**Comment by shenghsiaowong** [comment]
have you already got the demo for testing a image?

**Comment by shenghsiaowong** [comment]
> Yes, I have the same question.

have you already got the demo for testing a image?
