### ISSUE TITLE
dataset，dataloader

### ISSUE THREAD

**Issue by zkloveai** [TencentYoutuResearch/ObjectDetection-OneStageDet#23]
你好。首先感谢您的出色的工作。
我有一个问题。在您的_dataloading.py中的Dataset类中。返回的是self.input_dim，没有返回（(image, anno)），那网络如何得到(image, anno)。
我是想实现多尺度训练的。想不同batch的尺寸不同(320~608)。

**Comment by zkloveai** [comment]
还有一个，您的_dataloading.py里的函数change_input_dim是在哪里用到的。我没有找的调用他的代码。

**Comment by mileistone** [comment]
multi-scale training is supported, you'd better read the code again.
