### ISSUE TITLE
安装底下的提示命令，　make时候提示找不到CUDA, 用的是笔记本，没有ＣＵＤＡ

### ISSUE THREAD

**Issue by freeDevelope** [TencentYoutuResearch/ObjectDetection-OneStageDet#30]

**Comment by mileistone** [comment]
you can use a pure python version nms like [this](https://github.com/TencentYoutuResearch/ObjectDetection-OneStageDet/blob/master/yolo/utils/test/nms/py_cpu_nms.py) which doesn't need compilation.
