### ISSUE TITLE
an illegal memory access

### ISSUE THREAD

**Issue by ZHuiLBo** [TencentYoutuResearch/ObjectDetection-OneStageDet#31]
When i use tiny_yolov3.yml to train tiny yolov3 from scratch，i got the error：
![image](https://user-images.githubusercontent.com/28040964/51719006-c1c10300-2082-11e9-9838-f481137e2325.png)
What's going on?

**Comment by mileistone** [comment]
I didn't encounter this problem, and the information from this picture is so little, it's difficult to locate the problem. you may do some debugging work.
