### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: '/home/beichen2012/dataset/VOCdevkit/onedet_cache/train.pkl'

### ISSUE THREAD

**Issue by beichen2012** [TencentYoutuResearch/ObjectDetection-OneStageDet#38]
Got FileNotFoundError: [Errno 2] No such file or directory: '/home/beichen2012/dataset/VOCdevkit/onedet_cache/train.pkl'

when : python example/train.py Yolov3

**Comment by mileistone** [comment]
you may did't prepare `/home/beichen2012/dataset/VOCdevkit/onedet_cache/train.pkl` before training, you can read [this](https://github.com/TencentYoutuResearch/ObjectDetection-OneStageDet/tree/master/yolo#preparation) for details.

**Comment by zhuozhongshuo** [comment]
I also meet this problem. However, I found that you did not tell us to prepare `VOCdevkit/onedet_cache/train.pkl` in [this](https://github.com/TencentYoutuResearch/ObjectDetection-OneStageDet/tree/master/yolo#preparation).

**Comment by rlrahulkanojia** [comment]
link not available @mileistone

**Comment by mileistone** [comment]
> link not available @mileistone

please refer to https://github.com/mileistone/ObjectDetection-OneStageDet/tree/master/yolo
