### ISSUE TITLE
关于map

### ISSUE THREAD

**Issue by unsky** [TencentYoutuResearch/ObjectDetection-OneStageDet#39]
你好，感谢腾讯优图的分享，但是有一些以下问题：
1.从pre-trian训练和从初始训练是怎么定义的？如moblienet 是从imagenet训练来的还是 从初始训练
2.yolov3的性能感觉至少是可以对标ssd的，ssd从vgg16开始训练可以达到78+的map，但是看起来yolov3只能到60-70左右，这个问题请问有什么思考吗？

**Comment by dongfengxijian** [comment]
@unsky yolov3我看下面不是写着79%吗？你自己测试过吗？

**Comment by unsky** [comment]
79%的map是直接将darknet的模型加载来进行fineturn的？如果如此的话darknet的模型是从coco训练来的，
那这个结果就是coco+voc的训练数据才达到了79% 结果还是很差啊 @dongfengxijian

**Comment by dongfengxijian** [comment]
@unsky 效果这么差吗?我还以为darknet的模型是和VGG一样在ImageNet上训练的

**Comment by mileistone** [comment]
you can refer to the definition of `train from scratch`. I can get a 70% mAP use mobilenet when trained from scratch, but you only get 60%~70% mAP when using yolov3, I think you make some mistake.

**Comment by Stinky-Tofu** [comment]
> 你好，感谢腾讯优图的分享，但是有一些以下问题：
> 1.从pre-trian训练和从初始训练是怎么定义的？如moblienet 是从imagenet训练来的还是 从初始训练
> 2.yolov3的性能感觉至少是可以对标ssd的，ssd从vgg16开始训练可以达到78+的map，但是看起来yolov3只能到60-70左右，这个问题请问有什么思考吗？

不是这样的啊，darknet指的是darknet53，这只在ImageNet上训练过，没在COCO数据集上训练啊，我复现的代码用darknet初始化后，已经训到81了（用一些新文章对YOLO进行了改进）https://github.com/Stinky-Tofu/Stronger-yolo

**Comment by lc4321** [comment]
@Stinky-Tofu https://github.com/Stinky-Tofu/Stronger-yolo 打不开了
