### ISSUE TITLE
Undefined name 'hsv' in ./yolo/vedanet/data/transform/_preprocess.py

### ISSUE THREAD

**Issue by cclauss** [TencentYoutuResearch/ObjectDetection-OneStageDet#4]
__hsv__ is an _undefined name_ in this context: https://github.com/TencentYoutuResearch/ObjectDetection-OneStageDet/blob/master/yolo/vedanet/data/transform/_preprocess.py#L470

[flake8](http://flake8.pycqa.org) testing of https://github.com/TencentYoutuResearch/ObjectDetection-OneStageDet

$ __flake8 . --count --select=E901,E999,F821,F822,F823 --show-source --statistics__
```
./yolo/vedanet/data/transform/_preprocess.py:470:33: F821 undefined name 'hsv'
        img[:, :, 0] = wrap_hue(hsv[:, :, 0] + (360.0 * dh))
                                ^
1     F821 undefined name 'hsv'
1
```

__E901,E999,F821,F822,F823__ are the "_showstopper_" [flake8](http://flake8.pycqa.org) issues that can halt the runtime with a SyntaxError, NameError, etc. Most other flake8 issues are merely "style violations" -- useful for readability but they do not effect runtime safety.
* F821: undefined name `name`
* F822: undefined name `name` in `__all__`
* F823: local variable name referenced before assignment
* E901: SyntaxError or IndentationError
* E999: SyntaxError -- failed to compile a file into an Abstract Syntax Tree

**Comment by mileistone** [comment]
I'll fix it later, thank you.
