### ISSUE TITLE
Loss Plots and mAP Plots

### ISSUE THREAD

**Issue by glenn-jocher** [TencentYoutuResearch/ObjectDetection-OneStageDet#41]
Can you plot your losses and mAP vs batch/epoch, as in this PyTorch YOLOv3 repo?

https://github.com/ultralytics/yolov3
![](https://user-images.githubusercontent.com/26833433/49822374-3b27bf00-fd7d-11e8-9180-f0ac9fe2fdb4.png)

**Comment by mileistone** [comment]
maybe later

**Comment by shenghsiaowong** [comment]
have you plot it ?

**Comment by mileistone** [comment]
you can plot it yourself




| |
Jonathan
|
|
邮箱：xyc_sjtu@163.com
|

Signature is customized by Netease Mail Master

On 06/24/2019 09:00, shenghsiaowong wrote:

have you plot it ?

**Comment by shenghsiaowong** [comment]
thank you for your reply

**Comment by shenghsiaowong** [comment]
> you can plot it yourself | | Jonathan | | 邮箱：xyc_sjtu@163.com | Signature is customized by Netease Mail Master On 06/24/2019 09:00, shenghsiaowong wrote: have you plot it ? — You are receiving this because you modified the open/close state. Reply to this email directly, view it on GitHub, or mute the thread.

thank you for your reply

**Comment by shenghsiaowong** [comment]
> Can you plot your losses and mAP vs batch/epoch, as in this PyTorch YOLOv3 repo?
> 
> https://github.com/ultralytics/yolov3
> ![](https://user-images.githubusercontent.com/26833433/49822374-3b27bf00-fd7d-11e8-9180-f0ac9fe2fdb4.png)

have you plot it ?
