### ISSUE TITLE
训练自己的数据集

### ISSUE THREAD

**Issue by qhykwsw** [TencentYoutuResearch/ObjectDetection-OneStageDet#43]
谢谢大佬的贡献，我向请问下如果把自己的数据集制作成标准的VOC格式，然后要用YOLOV3进行训练。
目前我能想到的修改有：
（1）首先改动yolov3.yml中的“labels”和“data_root_dir”以及一些超参数，
（2）还有在_yolov3.py修改
num_classes=数据集对应的种类数
想问下还需要改动什么么？

另外，mobilenet, mobilenetv2, shufflenet(g2), shufflenetv2(1x), squeezenext(1.0-SqNxt-23v5), light xception, xception这些模型的权重文件可否提供一下呢？

**Comment by mileistone** [comment]
I think you should modify the following:
1, `labels`, `data_root_dir` and other hyper parameters in yolov3.yml
2, if you need, you may modify `anchors`, `thresh` in loss

You don't need modify the `num_classes` which can be deduced from `labels` in yolov3.yml

**Comment by qhykwsw** [comment]
Thank your for your reply. I have trained the model on my own dataset.

**Comment by hh7383** [comment]
> Thank your for your reply. I have trained the model on my own dataset.

我也在训练自己的数据集，有些问题想向你请教，请问你的数据集怎么制作放置的为什么我按照VOC2007的数据放置且按照readme的设置后，在执行python examples/train.py Yolov2时出现了FileNotFoundError: [Errno 2] No such file or directory: '/VOCdevkit/train/JPEGImages/0112.jpg'的问题，train文件目录是怎么来的？我并没有在VOCdevkit中创建过train文件夹。

**Comment by chakkritte** [comment]
@qhykwsw Could you tell me about your own datasets are VOC format (XML) or YOLO format (txt)?

Thank you.

**Comment by Aurorayy** [comment]
> > Thank your for your reply. I have trained the model on my own dataset.
> 
> 我也在训练自己的数据集，有些问题想向你请教，请问你的数据集怎么制作放置的为什么我按照VOC2007的数据放置且按照readme的设置后，在执行python examples/train.py Yolov2时出现了FileNotFoundError: [Errno 2] No such file or directory: '/VOCdevkit/train/JPEGImages/0112.jpg'的问题，train文件目录是怎么来的？我并没有在VOCdevkit中创建过train文件夹。

请问您解决了吗
