### ISSUE TITLE
检测结果中出现了置信度很低的bbox

### ISSUE THREAD

**Issue by qhykwsw** [TencentYoutuResearch/ObjectDetection-OneStageDet#45]
你好，我在使用代码的过程中发现，虽然经过NMS去重，还是会有一些置信度不一，但都是对同一个物体的bbox依然被写入到检测结果中。
比如使用YoloV3在VOC数据集上进行训练，测试得到的“comp4_det_test_aeroplane.txt”文件中，对000521.jpg检测到了3个bbox，结果如下：

000521 0.735211 249.26878 120.09045 318.2519 236.4592
000521 0.136427 272.41382 144.24376 324.67673 253.31178
000521 0.011197 244.49088 127.17586 298.92145 170.71593

既有置信度相对较高的，也有很低的。其中000521.jpg是一张只包含了一架飞机的图片。

我注意到，如果多次检测到同一个目标，在使用官方提供的voc_eval.py脚本进行评估时，可能会“虚假地提高”mAP。

所以请问：
1、对于检测深度学习模型的效果来说，是不是后续的mAP就直接在其基础上进行计算呢？还是说要进一步手动设置置信度的阈值（默认值是0.005），来对结果进行进一步筛选呢？
2、一般论文中对于这种“虚假地提高”mAP的做法是怎样的呢？是只计算一次么？

**Comment by mileistone** [comment]
confidence thresh will affect the mAP, if we set confidence lower, we will get higher mAP. 0.005 is lower enough for confidence thresh.
