### ISSUE TITLE
请问input_shape的选择有什么技巧么？

### ISSUE THREAD

**Issue by qhykwsw** [TencentYoutuResearch/ObjectDetection-OneStageDet#50]
现在对于input_shape对于结果的影响比较困惑，请指教。
我是在自己的数据集上测试，分辨率是[1280, 960]，训练时input_shape设置为[608, 456]比[608, 608]要好。测试时input_shape设置地越大，结果越好，比如[960, 960]。

**Comment by aragornpangit** [comment]
一 建议你在训练之前，把图片裁为正方形，再标注。推理时也用正方形
二 分辨率越大，当然效果越好
