### ISSUE TITLE
The problem of eval speed

### ISSUE THREAD

**Issue by LDoubleZhi** [TencentYoutuResearch/ObjectDetection-OneStageDet#51]
I write a img_detect func which detect per img, so I have not use dataloader. The other code is same to yours. when I test on 1080ti, I get only 0.05s/per img.Is the problem is whether using dataloader?

**Comment by FoolishMao** [comment]
speed.py do not do any postprocess, maybe it's the difference.

**Comment by Stinky-Tofu** [comment]
把conf_threshold设置为0.2以上，速度就上来了，因为conf_threshold越低mAP越高，但是速度越慢（需要NMS大量的bbox）

**Comment by LDoubleZhi** [comment]
> 把conf_threshold设置为0.2以上，速度就上来了，因为conf_threshold越低mAP越高，但是速度越慢（需要NMS大量的bbox）

对的，还有就是后处理的锅了（笑哭）

**Comment by qhykwsw** [comment]
> I write a img_detect func which detect per img, so I have not use dataloader. The other code is same to yours. when I test on 1080ti, I get only 0.05s/per img.Is the problem is whether using dataloader?

楼主可以把你的检测代码分享给我么，我的邮箱是1425751338@qq.com，我这边写了一个可以画pr曲线输出mAP的代码，如果你有需要，我也可以发给你，不甚感谢。

**Comment by wangg12** [comment]
@qhykwsw @Stinky-Tofu Could you kindly share your code for calculating mAP?

**Comment by Stinky-Tofu** [comment]
@wangg12 https://github.com/Stinky-Tofu/Stronger-yolo

**Comment by qhykwsw** [comment]
> @qhykwsw @Stinky-Tofu Could you kindly share your code for calculating mAP?
给我你的邮箱？

**Comment by wangg12** [comment]
@Stinky-Tofu Thanks, I will have a try.

**Comment by wangg12** [comment]
@qhykwsw My email is guwang12@foxmail.com. Thanks.

**Comment by shenghsiaowong** [comment]
@LDoubleZhi 你好可以发我一份你的检测代码吗？wang1540266695@163.com,我这边加了focalloaa 以及cbam的代码，你需要我也可以发你

**Comment by LDoubleZhi** [comment]
翻邮件才看到。。




------------------ 原始邮件 ------------------
发件人: "shenghsiaowong"<notifications@github.com>;
发送时间: 2019年6月22日(星期六) 下午4:49
收件人: "TencentYoutuResearch/ObjectDetection-OneStageDet"<ObjectDetection-OneStageDet@noreply.github.com>;
抄送: "柳林志"<3190554979@qq.com>;"Mention"<mention@noreply.github.com>;
主题: Re: [TencentYoutuResearch/ObjectDetection-OneStageDet] The problem ofeval speed (#51)




@LDoubleZhi 你好可以发我一份你的检测代码吗？wang1540266695@163.com,我这边加了focalloaa 以及cbam的代码，你需要我也可以发你

**Comment by lc4321** [comment]
@LDoubleZhi 你好，可以发我一份你的检测代码吗？licuicqu@163.com,谢谢了
