### ISSUE TITLE
why cls loss use softmax ? can this support multi label to one box in prediction

### ISSUE THREAD

**Issue by Tveek** [TencentYoutuResearch/ObjectDetection-OneStageDet#52]
Original paper for this:
YOLOv3 predicts an objectness score for each bounding box using logistic regression.
But,yours:
https://github.com/TencentYoutuResearch/ObjectDetection-OneStageDet/blob/master/yolo/vedanet/loss/_yololoss.py#L133

**Comment by mileistone** [comment]
I tried both, and found softmax converges better.
