### ISSUE TITLE
Something wrong with the utils/test make -j32

### ISSUE THREAD

**Issue by GUOShuxuan** [TencentYoutuResearch/ObjectDetection-OneStageDet#53]
Hi, I am trying your codes now. I am facing an make error when do 'make -j32'. Could please give me some suggestions, like the version of gcc?

**Comment by GUOShuxuan** [comment]
Solved.

**Comment by tzc1994** [comment]
Hello, I meet errors in making also. How dou you fix it ?

8 errors detected in the compilation of "/tmp/tmpxft_00000f03_00000000-6_nms_kernel.cpp1.ii".
error: command '/usr/local/cuda-9.0/bin/nvcc' failed with exit status 1
Makefile:2: recipe for target 'all' failed
make: *** [all] Error 1
