### ISSUE TITLE
During the test phase, did you remove the bbox marked as "difficult"?

### ISSUE THREAD

**Issue by Stinky-Tofu** [TencentYoutuResearch/ObjectDetection-OneStageDet#9]
During the test phase, did you remove the bbox marked as "difficult"?

**Comment by mileistone** [comment]
you can refer to the mAP calculation utils like [this](https://github.com/rbgirshick/py-faster-rcnn/blob/master/lib/datasets/voc_eval.py) for details.

**Comment by Stinky-Tofu** [comment]
> you can refer to the mAP calculation utils like [this](https://github.com/rbgirshick/py-faster-rcnn/blob/master/lib/datasets/voc_eval.py) for details.

Thank you!
